spring:
  datasource:
    url: jdbc:h2:file:./target/db/petclinic;AUTOCOMMIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    tomcat:
      default-auto-commit: false
server:
  port: 8090
petclinic:
  send-sqllog: true
  db-auto-init: true
  enabled-auth: false
  jwt-secret-key: 61ce8046e3fab53138497a3a8593825548f2744d5bc4d529b5945fd4a4bd991a

